import Phaser from 'phaser';

const BG   = 0x0c0906;
const GOLD = '#b87820';
const DIM  = '#555555';
const MID  = '#888888';

export class CreditsScene extends Phaser.Scene {
  constructor() {
    super({ key: 'CreditsScene' });
  }

  create(): void {
    const { width, height } = this.scale;
    const cx = width / 2;

    this.add.rectangle(0, 0, width, height, BG).setOrigin(0);

    // Title
    this.add.text(cx, 48, 'CREDITS', {
      fontSize: '28px', fontFamily: 'monospace', fontStyle: 'bold', color: GOLD,
    }).setOrigin(0.5);

    const lines: Array<{ text: string; style?: object }> = [
      { text: 'GAME',          style: { color: GOLD,  fontSize: '13px', fontStyle: 'bold' } },
      { text: 'Steamheart Engine — Max Basev',     style: { color: MID } },
      { text: 'Gamedev.js Jam 2026  ·  theme: Machines', style: { color: DIM } },

      { text: '' },

      { text: 'CODE & FRAMEWORKS',                 style: { color: GOLD, fontSize: '13px', fontStyle: 'bold' } },
      { text: 'Phaser 3.80.1  —  MIT License',    style: { color: MID } },
      { text: 'TypeScript 5.4.5  —  Apache 2.0',  style: { color: MID } },
      { text: 'Vite 5.2.0  —  MIT License',        style: { color: MID } },

      { text: '' },

      { text: 'ART',    style: { color: GOLD, fontSize: '13px', fontStyle: 'bold' } },
      { text: 'All sprites and visual assets',     style: { color: MID } },
      { text: 'generated by Max Basev using Google Gemini', style: { color: MID } },

      { text: '' },

      { text: 'AUDIO',  style: { color: GOLD, fontSize: '13px', fontStyle: 'bold' } },
      { text: 'Background music — Google Gemini',  style: { color: MID } },
      { text: 'Sound effects — Suno AI',           style: { color: MID } },
      { text: 'All audio by Max Basev',            style: { color: MID } },
    ];

    const base = { fontSize: '13px', fontFamily: 'monospace', color: MID };
    let y = 108;
    const lineH = 22;

    for (const line of lines) {
      if (!line.text) { y += lineH * 0.6; continue; }
      this.add.text(cx, y, line.text, { ...base, ...line.style }).setOrigin(0.5);
      y += lineH;
    }

    // Back button
    const back = this.add.text(cx, height - 44, '←  BACK', {
      fontSize: '15px', fontFamily: 'monospace', color: '#333333',
    }).setOrigin(0.5).setInteractive({ useHandCursor: true });

    back.on('pointerover',  () => back.setColor(GOLD));
    back.on('pointerout',   () => back.setColor('#333333'));
    back.on('pointerdown',  () => this.scene.start('MainMenuScene'));

    this.input.keyboard!.on('keydown-ESC',   () => this.scene.start('MainMenuScene'));
    this.input.keyboard!.on('keydown-SPACE', () => this.scene.start('MainMenuScene'));
  }
}
